[env]
EDITOR = "nvim"
KUBE_EDITOR = "nvim"
K9S_FEATURE_GATE_NODE_SHELL = "true"

[tasks.update]
quiet = true
description = "Update apt packages and upgrade mise itself + all mise-managed tools"
run = "sudo apt update && sudo apt upgrade -y && mise self-update -y && mise upgrade"

[tools]
ast-grep = "latest"
chezmoi = "latest"
helm = "latest"
herdr = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "24"
starship = "latest"
stern = "latest"
tree-sitter = "latest"
usage = "latest"
yazi = "latest"
yq = "latest"
zellij = "latest"

[settings]
experimental = true
