[tools]
ast-grep = "latest"
chezmoi = "latest"
helm = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "24"
usage = "latest"
yazi = "latest"
yq = "latest"
