[env]
EDITOR = "nvim"
KUBE_EDITOR = "nvim"
K9S_FEATURE_GATE_NODE_SHELL = "true"

[tasks.full-upgrade]
quiet = true
description = "Update apt packages and all mise-managed tools"
run = "sudo apt update && sudo apt full-upgrade -y && mise self-update -y && mise upgrade"

[tools]
age = "latest"
ast-grep = "latest"
bat = "latest"
btop = "latest"
chezmoi = "latest"
eza = "latest"
fd = "latest"
flux2 = "latest"
fzf = "latest"
helm = "latest"
herdr = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
lazydocker = "latest"
lazygit = "latest"
mkcert = "latest"
neovim = "latest"
node = "24"
ripgrep = "latest"
starship = "latest"
tree-sitter = "latest"
usage = "latest"
yazi = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"

[settings]
experimental = true
